project_id = "ydoaxvfdhyadzzxdsilv"

[functions.ai-partner-search]
verify_jwt = false

[functions.calculate-matches]
verify_jwt = false

[functions.ai-partner-recommendations]
verify_jwt = true

[functions.translate-message]
verify_jwt = true

[functions.import-companies]
verify_jwt = false

